{"timestamp":"2025-07-11T15:54:50.965849","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T15:54:50.966206","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/bank_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T15:54:50.990639Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:50.990776Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:50.990827Z","level":"info","event":"Current task name:start_log","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:50.990872Z","level":"info","event":"Dag name:bank_data_etl_process","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:50.995535","level":"info","event":"Connection Retrieved 'postgres_bank_logs'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-11T15:54:51.017010Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021201Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021280Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): start_log>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021326Z","level":"info","event":"Failure caused by Не удалось залогировать старт: (psycopg2.errors.InsufficientPrivilege) permission denied for schema logs","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021372Z","level":"info","event":"LINE 1: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status)...","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021414Z","level":"info","event":"                    ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021455Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021495Z","level":"info","event":"[SQL: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status) VALUES ('Airflow_Full_ETL', %(start_time)s, 'STARTED') RETURNING log_id;]","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021534Z","level":"info","event":"[parameters: {'start_time': datetime.datetime(2025, 7, 11, 15, 54, 51, 13126)}]","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.021572Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T15:54:51.016375","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowFailException","exc_value":"Не удалось залогировать старт: (psycopg2.errors.InsufficientPrivilege) permission denied for schema logs\nLINE 1: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status)...\n                    ^\n\n[SQL: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status) VALUES ('Airflow_Full_ETL', %(start_time)s, 'STARTED') RETURNING log_id;]\n[parameters: {'start_time': datetime.datetime(2025, 7, 11, 15, 54, 51, 13126)}]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":57,"name":"start_log"}],"is_group":false,"exceptions":[]},{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.InsufficientPrivilege) permission denied for schema logs\nLINE 1: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status)...\n                    ^\n\n[SQL: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status) VALUES ('Airflow_Full_ETL', %(start_time)s, 'STARTED') RETURNING log_id;]\n[parameters: {'start_time': datetime.datetime(2025, 7, 11, 15, 54, 51, 13126)}]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":51,"name":"start_log"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py","lineno":334,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1577,"name":"_execute_clauseelement"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"InsufficientPrivilege","exc_value":"permission denied for schema logs\nLINE 1: INSERT INTO LOGS.ETL_LOGS (process_name, start_time, status)...\n                    ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
