{"timestamp":"2025-07-11T21:43:05.079279","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T21:43:05.079465","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/bank_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T21:43:05.104693Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:05.105565Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:05.105654Z","level":"info","event":"Current task name:extract_transform_load","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:05.105712Z","level":"info","event":"Dag name:bank_data_etl_process","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:05.107713","level":"info","event":"Connection Retrieved 'postgres_bank_ds'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-11T21:43:05.108174","level":"info","event":"Пауза 5 секунд для наглядности логов...","logger":"root"}
{"timestamp":"2025-07-11T21:43:10.108502","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_account_d.csv для таблицы MD_ACCOUNT_D =====","logger":"root"}
{"timestamp":"2025-07-11T21:43:10.117244","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:76: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T21:43:10.144640","level":"error","event":"ОШИБКА ВНУТРИ ETL ЗАДАЧИ: (psycopg2.errors.InsufficientPrivilege) permission denied for schema DS\nLINE 2: CREATE TABLE \"DS\".temp_md_account_d (\n                     ^\n\n[SQL: \nCREATE TABLE \"DS\".temp_md_account_d (\n\tdata_actual_date TIMESTAMP WITHOUT TIME ZONE, \n\tdata_actual_end_date TIMESTAMP WITHOUT TIME ZONE, \n\taccount_rk BIGINT, \n\taccount_number TEXT, \n\tchar_type TEXT, \n\tcurrency_rk BIGINT, \n\tcurrency_code BIGINT\n)\n\n]\n(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"root"}
{"timestamp":"2025-07-11T21:43:10.145608Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.145716Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.145819Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): extract_transform_load>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.145908Z","level":"info","event":"Failure caused by ETL процесс провалился с ошибкой: (psycopg2.errors.InsufficientPrivilege) permission denied for schema DS","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.145993Z","level":"info","event":"LINE 2: CREATE TABLE \"DS\".temp_md_account_d (","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146074Z","level":"info","event":"                     ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146152Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146230Z","level":"info","event":"[SQL:","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146306Z","level":"info","event":"CREATE TABLE \"DS\".temp_md_account_d (","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146398Z","level":"info","event":"\tdata_actual_date TIMESTAMP WITHOUT TIME ZONE,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146473Z","level":"info","event":"\tdata_actual_end_date TIMESTAMP WITHOUT TIME ZONE,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146547Z","level":"info","event":"\taccount_rk BIGINT,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146628Z","level":"info","event":"\taccount_number TEXT,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146758Z","level":"info","event":"\tchar_type TEXT,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146833Z","level":"info","event":"\tcurrency_rk BIGINT,","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146910Z","level":"info","event":"\tcurrency_code BIGINT","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.146983Z","level":"info","event":")","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.147054Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.147132Z","level":"info","event":"]","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.147206Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:43:10.144759","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowFailException","exc_value":"ETL процесс провалился с ошибкой: (psycopg2.errors.InsufficientPrivilege) permission denied for schema DS\nLINE 2: CREATE TABLE \"DS\".temp_md_account_d (\n                     ^\n\n[SQL: \nCREATE TABLE \"DS\".temp_md_account_d (\n\tdata_actual_date TIMESTAMP WITHOUT TIME ZONE, \n\tdata_actual_end_date TIMESTAMP WITHOUT TIME ZONE, \n\taccount_rk BIGINT, \n\taccount_number TEXT, \n\tchar_type TEXT, \n\tcurrency_rk BIGINT, \n\tcurrency_code BIGINT\n)\n\n]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":100,"name":"extract_transform_load"}],"is_group":false,"exceptions":[]},{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.InsufficientPrivilege) permission denied for schema DS\nLINE 2: CREATE TABLE \"DS\".temp_md_account_d (\n                     ^\n\n[SQL: \nCREATE TABLE \"DS\".temp_md_account_d (\n\tdata_actual_date TIMESTAMP WITHOUT TIME ZONE, \n\tdata_actual_end_date TIMESTAMP WITHOUT TIME ZONE, \n\taccount_rk BIGINT, \n\taccount_number TEXT, \n\tchar_type TEXT, \n\tcurrency_rk BIGINT, \n\tcurrency_code BIGINT\n)\n\n]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":86,"name":"extract_transform_load"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3008,"name":"to_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":788,"name":"to_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":1948,"name":"to_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":1852,"name":"prep_table"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":936,"name":"create"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":922,"name":"_execute_create"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py","lineno":962,"name":"create"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2221,"name":"_run_ddl_visitor"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py","lineno":524,"name":"traverse_single"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py","lineno":899,"name":"visit_table"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py","lineno":80,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1477,"name":"_execute_ddl"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"InsufficientPrivilege","exc_value":"permission denied for schema DS\nLINE 2: CREATE TABLE \"DS\".temp_md_account_d (\n                     ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
